---
title: "V5_DeviationChangeByAge"
author: "Xiaoyu Xu"
date: "2025-06-16"
output: html_document
---

This script is to test whether the deviations or normalized symptoms decreased with age in ADHD group.

```{r setup, include=FALSE}
rm(list=ls())
library(mgcv)
library(parallel)
library(tidyverse)
library(patchwork)
# set resolution
Yeoresolution <- 17
if (Yeoresolution == 7){
  Yeoresolution.delLM = 6
}else if (Yeoresolution == 17){
  Yeoresolution.delLM = 15
}
element_num <- Yeoresolution.delLM*(Yeoresolution.delLM+1)/2

# input directory
wd <- getwd()
homepath <- str_split_i(wd, "Normative_model", 1)
demopath <- paste0(homepath, '/Normative_model/demography')
interfileFolder <- paste0(homepath, '/Normative_model/interfileFolder_EFNYnoCCNP')
interfileFolder_ABCD <- paste0(homepath, '/Normative_model/interfileFolder_ABCD')
functionFolder <- paste0(homepath, "/Normative_model/functions")
resultFolder <- paste0(homepath, "/Normative_model/results_EFNYnoCCNP")
resultFolder_ABCD <- paste0(homepath, "/Normative_model/results_ABCD")
functionFolder.SCDev <- paste0(homepath, "/SC_development/Rcode_SCdevelopment/gamfunction")
FigureFolder <- paste0(homepath, '/Normative_model/Figures_EFNYnoCCNP/Yeo', Yeoresolution,'/CV75')

source(paste0(functionFolder.SCDev, "/gamsmooth.R"))
source(paste0(functionFolder, "/plotmatrix.R"))
source(paste0(functionFolder, "/index2network.R"))
source(paste0(functionFolder.SCDev, "/plotdata_generate.R"))
source(paste0(functionFolder.SCDev, "/SCrankcorr.R"))
source(paste0(functionFolder.SCDev, '/gamderivatives.R'))
# Load data
SCdata <- readRDS(paste0(interfileFolder, '/SCdata_Yeo',Yeoresolution, '_CV75_deviations_all.rds'))

Behavior <- read.csv(paste0(demopath, "/basic_demo_PKU6_addSymptom.csv"))
Behavior$ID <- paste0("sub-", Behavior$ID)
SCdata <- SCdata %>% left_join(dplyr::select(Behavior, ID, medication, IA_B, HI_B, TO_B, IA_F, HI_F, TO_F, IA_B.norm, HI_B.norm, TO_B.norm, RVPA, RVPML, RVPTFA, RVPTM, RVPTH, RVPPH, SSTSSRT, SSTDEG, SSTDES, SWMBE, ICV), by="ID")
SCdata$sex <- as.factor(SCdata$sex)
SCdata$diagnosis <- factor(SCdata$diagnosis, levels = c("TD", "ADHD"))
table(SCdata$diagnosis, SCdata$site)

SCdata.ADHD <- SCdata %>% filter(diagnosis == "ADHD", visit=="0")
SCdata.TD <- SCdata %>% filter(diagnosis == "TD")

# Deviation by Age
gamresultsum.df.ADHD.ABCD <- readRDS(paste0(interfileFolder_ABCD, '/AllSCDeviation_NormSymptom_Age_Yeo', Yeoresolution,'_CV75_ADHD.rds'))
gamresultsum.df.ADHD.ABCD.SC <- gamresultsum.df.ADHD.ABCD[str_detect(gamresultsum.df.ADHD.ABCD$parcel, "SC."),]
gamresultsum.df.ADHD.ABCD.SC$bootstrap_p.fdr <- p.adjust(gamresultsum.df.ADHD.ABCD.SC$bootstrap_pvalue, method="fdr")
interaction.df.ABCD <- readRDS(paste0(interfileFolder_ABCD, "/Deviation_TDtest-ADHDall_SC", element_num,".rds"))
interaction.df.ABCD <- interaction.df.ABCD[seq(from=2, to=2*element_num, by = 2),]

interaction.df.ABCD <- interaction.df.ABCD %>% filter(parcel %in% gamresultsum.df.ADHD.ABCD.SC$parcel[gamresultsum.df.ADHD.ABCD.SC$bootstrap_p.fdr<0.05])

interaction.df.ABCD$bootstrap_pvalue.fdr <- p.adjust(interaction.df.ABCD$bootstrap_pvalue, method = "fdr")

sigedge.all.ABCD <- interaction.df.ABCD$parcel[interaction.df.ABCD$bootstrap_pvalue.fdr < 0.05]

# PKU6 interaction effect
interaction.df <- readRDS(paste0(interfileFolder, "/Deviation_TDtest-ADHDall_SC", element_num,".rds"))
interaction.df <- interaction.df[seq(from=2, to=2*element_num, by = 2),]

```

## Test the age effects

The dependent variables will be the deviations of SC exhibiting significant group-wise difference and the normalized symptom scores.

```{r development}
covariates<-"sex+mean_fd"
dataname.list <- c("SCdata.ADHD", "SCdata.TD")
smooth_var<-"age"
# sigedge.all <- diffbyage$parcel
# sigedge.all <- gsub("_h", "_deviationZ", sigedge.all)
symptomvar <- c("IA_B", "HI_B", "TO_B")
dependent.var <- c(paste0("SC.", 1:element_num, "_deviationZ"), symptomvar)


for (dataname in dataname.list){
  if (!file.exists(paste0(interfileFolder, '/AllSCDeviation_NormSymptom_Age_Yeo', Yeoresolution,'_CV75_',str_split_i(dataname, "SCdata.", 2), '_all.rds'))){
    print(dataname)
    if (str_detect(dataname, "TD")){dependent.var.f <- paste0("SC.", 1:element_num, "_deviationZ")}else{dependent.var.f <- dependent.var}
    
    resultsum <- mclapply(1:length(dependent.var.f), function(x){
      region<-dependent.var[x]
      gamresult<-gam.fit.smooth(region, dataname, smooth_var, covariates, knots=3, set_fx = T, stats_only = T, mod_only = FALSE)
      gamresult<-as.data.frame(gamresult)
      return(gamresult)
    }, mc.cores = 30)
    
    gamresultsum.df <- do.call(rbind, lapply(resultsum, function(x) data.frame(x)))
    gamresultsum.df[,c(2:10)]<-lapply(gamresultsum.df[,c(2:10)], as.numeric)
    
    saveRDS(gamresultsum.df, paste0(interfileFolder, '/AllSCDeviation_NormSymptom_Age_Yeo', Yeoresolution,'_CV75_',str_split_i(dataname, "SCdata.", 2), '_all.rds'))
  }
}

gamresultsum.df.ADHD <- readRDS(paste0(interfileFolder, '/AllSCDeviation_NormSymptom_Age_Yeo', Yeoresolution,'_CV75_ADHD_all.rds'))
gamresultsum.df.TD <- readRDS(paste0(interfileFolder, '/AllSCDeviation_NormSymptom_Age_Yeo', Yeoresolution,'_CV75_TD_all.rds'))

gamresultsum.df.ADHD.SC <- gamresultsum.df.ADHD[str_detect(gamresultsum.df.ADHD$parcel, "SC."),]
gamresultsum.df.ADHD.SC$bootstrap_p.fdr <- p.adjust(gamresultsum.df.ADHD.SC$anova.smooth.pvalue, method="fdr")
summary(gamresultsum.df.ADHD.SC)
SCrankcorr(gamresultsum.df.ADHD.SC, "partialRsq", Yeoresolution.delLM)
#   ds.resolution Interest.var r.spearman   p.spearman
# 1            15   partialRsq -0.3544105 7.143925e-05

gamresultsum.df.TD$bootstrap_p.fdr <- p.adjust(gamresultsum.df.TD$anova.smooth.pvalue, method = "fdr")
SCrankcorr(gamresultsum.df.TD, "partialRsq", Yeoresolution.delLM)
#   ds.resolution Interest.var r.spearman p.spearman
# 1            15   partialRsq 0.07304132  0.4278871


Int.results.df_final2 <- interaction.df %>% filter(parcel %in% gamresultsum.df.ADHD.SC$parcel[gamresultsum.df.ADHD.SC$bootstrap_p.fdr<0.05])

Int.results.df_final2$anova.int.pvalue.fdr <- p.adjust(Int.results.df_final2$anova.int.pvalue, method = "fdr")
print(paste(sum(Int.results.df_final2$anova.int.pvalue.fdr < 0.05), "edges have significant group-wise difference."))
# 7 edges have significant group-wise difference.

# Overlap with ABCD
gamresultsum.df.ADHD.SC.ABCDsig <- gamresultsum.df.ADHD.SC %>% filter(parcel %in% sigedge.all.ABCD)
gamresultsum.df.ADHD.SC.ABCDsig$bootstrap_p.fdr <- p.adjust(gamresultsum.df.ADHD.SC.ABCDsig$anova.smooth.pvalue, method="fdr")
summary(gamresultsum.df.ADHD.SC.ABCDsig)

gamresultsum.df.ADHD.SC.ABCDsig <- gamresultsum.df.ADHD.SC.ABCDsig %>% filter(bootstrap_p.fdr < 0.05)

# Int.results.df_final3 <- interaction.df %>% filter(parcel %in% gamresultsum.df.ADHD.SC.ABCDsig$parcel)
# 
# Int.results.df_final3$anova.int.pvalue.fdr <- p.adjust(Int.results.df_final3$anova.int.pvalue, method = "fdr")
# print(paste(sum(Int.results.df_final3$anova.int.pvalue.fdr < 0.05), "edges have significant group-wise difference."))
# 
# gamresultsum.df.ADHD.SC.ABCDsig <- gamresultsum.df.ADHD.SC.ABCDsig %>% filter(parcel %in% Int.results.df_final3$parcel[Int.results.df_final3$anova.int.pvalue.fdr < 0.05])

```

## Plot the trajectories
```{r}
### plot the figures for SC
## Models
for (dataname in dataname.list){
  resultsum <- list()
  for (x in 1:nrow(gamresultsum.df.ADHD.SC.ABCDsig)){
    region<-gamresultsum.df.ADHD.SC.ABCDsig$parcel[x]
    gamresult<-gam.fit.smooth(region, dataname, smooth_var, covariates, knots=3, set_fx = T, stats_only = F, mod_only = T)
    resultsum[[x]] <- gamresult
  }
  saveRDS(resultsum, paste0(interfileFolder, '/gammodelSigDiagnoseSCDeviation_NormSymptom_Age_Yeo', Yeoresolution,'_CV75_',str_split_i(dataname, "SCdata.", 2),'_all.rds'))
}
gammod.ADHD <- readRDS(paste0(interfileFolder, '/gammodelSigDiagnoseSCDeviation_NormSymptom_Age_Yeo', Yeoresolution,'_CV75_ADHD_all.rds'))
gammod.TD <- readRDS(paste0(interfileFolder, '/gammodelSigDiagnoseSCDeviation_NormSymptom_Age_Yeo', Yeoresolution,'_CV75_ADHD_all.rds'))

## Plot data
agevector <- seq(min(SCdata.ADHD$age), max(SCdata.ADHD$age), length.out=1000)

# ADHD
if (file.exists(paste0(interfileFolder, '/plotdatasum.df_Yeo', Yeoresolution, '_SCdeviation_CV75_ADHD.rds')) == F){
  plotdatasum.ADHD <- list()
  for (x in 1:nrow(gamresultsum.df.ADHD.SC.ABCDsig)){
    modobj <- gammod.ADHD[[x]]
    plotdata<- plotdata_generate(modobj, "SCdata.ADHD", "age", agevector)
    plotdata$SC_label <- names(plotdata)[ncol(plotdata)]
    plotdata[,ncol(plotdata)-1] <- NULL
    plotdatasum.ADHD[[x]] <- plotdata
  }
  
  plotdatasum.ADHD.df <- do.call(rbind, lapply(plotdatasum.ADHD, function(x) data.frame(x)))
  saveRDS(plotdatasum.ADHD.df, paste0(interfileFolder, '/plotdatasum.df_Yeo', Yeoresolution, '_SCdeviation_CV75_ADHD.rds'))
  
}else{
  plotdatasum.ADHD.df <- readRDS(paste0(interfileFolder, '/plotdatasum.df_Yeo', Yeoresolution, '_SCdeviation_CV75_ADHD.rds'))
}

## Derivative data
agevector <- seq(min(SCdata.ADHD$age), max(SCdata.ADHD$age), length.out=1000)

# ADHD
if (file.exists(paste0(interfileFolder, '/derivativedatasum.df_Yeo', Yeoresolution, '_sumSCinvnode_CV75_ADHD.rds')) == F){
  derivdatasum.ADHD <- list()
  for (x in 1:nrow(gamresultsum.df.ADHD.SC.ABCDsig)){
    modobj <- gammod.ADHD[[x]]
    draws<-1
    increments<-1000
    derivdata<- gam.derivatives(modobj, "age", agevector, draws, increments, return_posterior_derivatives = FALSE)
    derivdata$label_ID<-gamresultsum.df.ADHD.SC.ABCDsig$parcel[x]
    derivdatasum.ADHD[[x]] <- derivdata
  }
  
  derivdatasum.ADHD.df <- do.call(rbind, lapply(derivdatasum.ADHD, function(x) data.frame(x)))
  saveRDS(derivdatasum.ADHD.df, paste0(interfileFolder, '/derivativedatasum.df_Yeo', Yeoresolution, '_sumSCinvnode_CV75_ADHD.rds'))
}else{
  derivdatasum.ADHD.df <- readRDS(paste0(interfileFolder, '/derivativedatasum.df_Yeo', Yeoresolution, '_sumSCinvnode_CV75_ADHD.rds'))
}

derivdatasum.ADHD.df$se_CI <- (derivdatasum.ADHD.df$upper-derivdatasum.ADHD.df$lower) / (2*1.96)
derivdatasum.ADHD.df$p.value <- 2 * (1 - pnorm(abs(derivdatasum.ADHD.df$derivative / derivdatasum.ADHD.df$se_CI)))
summary(derivdatasum.ADHD.df$p.value)
derivdatasum.ADHD.df$significance_pvalue <- (derivdatasum.ADHD.df$p.value < 0.05)
derivdatasum.ADHD.df <- derivdatasum.ADHD.df %>% group_by(age) %>%
  mutate(fdr_pvalue = p.adjust(p.value, method="fdr")) %>% ungroup()
summary(derivdatasum.ADHD.df$fdr_pvalue)
derivdatasum.ADHD.df$significance_pvalue_fdr <- (derivdatasum.ADHD.df$fdr_pvalue < 0.05)
derivdatasum.ADHD.df$significant.derivative[which(derivdatasum.ADHD.df$significant.derivative==0)] <- NA
derivdatasum.ADHD.df$significant.derivative_fdr <- derivdatasum.ADHD.df$derivative
derivdatasum.ADHD.df$significant.derivative_fdr[which(derivdatasum.ADHD.df$significance_pvalue_fdr==F)] <- NA

## Figure out
rand.df <- data.frame(rand = rnorm(element_num, 0, 1))
Yeo_10 <- SCrankcorr(rand.df, "rand", Yeoresolution.delLM, T)
Yeo_10$SClabel <- paste0("SC.", 1:element_num)
for (x in 1:nrow(gamresultsum.df.ADHD.SC.ABCDsig)){
  region<-gamresultsum.df.ADHD.SC.ABCDsig$parcel[x]
  if (str_detect(gamresultsum.df.ADHD$parcel[x], "SC.")){
    label <- gsub("_deviationZ", "", region)
    SCrank.tmp <- Yeo_10$SCrank[Yeo_10$SClabel==label]
    gamresultsum.df.ADHD.SC$SCrank[x] <- SCrank.tmp
  }else{
      label <- region
    }
  
  
  data.ADHD <- plotdatasum.ADHD.df %>% filter(SC_label==region)
  data.ADHD$diagnosis <- "ADHD"
  
  # scatter plot
  scatterFig <- ggplot(data=data.ADHD)+
    geom_ribbon(aes(x=age, ymin=selo, ymax=sehi), fill="#810F7C", alpha=0.3)+
    geom_line(aes(x=age, y=fit), linewidth=1)+
    # scale_color_manual(values = c("black", "#810F7C"))+
    # scale_fill_manual(values = c("black", "#810F7C"))+
    scale_x_continuous(breaks = c(9, 11, 13, 15))+
    labs(x=NULL, y=label)+
    theme_classic()+
    theme(axis.text.y=element_text(size=24, color="black"), 
          axis.text.x = element_blank(),    # 隐藏标签
          axis.ticks.x = element_blank(),
          axis.title =element_text(size=24, color="black"),aspect.ratio = 1,
          plot.title = element_text(size=20.5, hjust=0.5, color="black"),
          plot.background=element_rect(fill="transparent"),
          panel.background=element_rect(fill="transparent"),
          legend.position = 'none')
  
  deriADHD <- derivdatasum.ADHD.df %>% filter(label_ID == region)
  deriADHD$significant.derivative_fdr[deriADHD$significance_pvalue_fdr==F] <- NA
  
  linerange_frame<-data.frame(x=c(min(deriADHD$age),max(deriADHD$age)), ymin =rep(0, times=2), ymax =rep(1, times=2),y=c(0, 1), xmin=rep(min(deriADHD$age), times=2), xmax=rep(max(deriADHD$age), times=2))
  maxth <- max(abs(deriADHD$significant.derivative_fdr), na.rm = T)
  minth <- min(deriADHD$significant.derivative_fdr, na.rm = T)
  
  # ADHD derivative
  derivplot.ADHD <-ggplot(data=deriADHD)+
    geom_bar(aes(x=age, y=1, fill = significant.derivative_fdr, color=significant.derivative_fdr),stat = "identity", position = "stack")+
    geom_linerange(data=linerange_frame, aes(y=y, xmin =xmin, xmax =xmax), color="black", linewidth=0.5)+
    geom_linerange(data=linerange_frame, aes(x=x, ymin =ymin, ymax =ymax), color="black", linewidth=0.5)+
    scale_color_distiller(type="seq", palette = "RdBu",limit=c(-maxth, maxth),na.value="white", direction = -1)+
    scale_fill_distiller(type="seq", palette = "RdBu",limit=c(-maxth, maxth),na.value="white", direction = -1)+
    scale_y_continuous(breaks =NULL)+
    ylab(NULL)+xlab("Age (years)")+
    #scale_x_continuous(breaks = c(9, 11, 13, 15))+
    theme_classic()+
    theme(axis.text=element_text(size=24, color='black'),
          axis.title = element_text(size = 24),
          axis.line.y=element_blank(),
          axis.line.x=element_blank(),aspect.ratio = 0.05,
          axis.ticks.y = element_blank(),
          legend.position = 'none')
  
  combined_plot <- scatterFig / derivplot.ADHD + plot_layout(ncol=1, nrow=2)
  print(combined_plot)
  
  #print(scatterFig)
  ggsave(paste0(FigureFolder, "/SCstrength_Age/Deviationcompare/DeviationChange/", region, "_noPoint.tiff"),combined_plot, width=13, height = 13, units = "cm")
  
  # Within ADHD
  SCdata.ADHD$Deviation <- SCdata.ADHD[[region]]
  SCdata.ADHD <- SCdata.ADHD %>% mutate(
    Deviation=case_when(
      Deviation > mean(Deviation)+3*sd(Deviation) ~ NA,
      Deviation < mean(Deviation)-3*sd(Deviation) ~ NA,
      .default = Deviation
    )
  )
  if (str_detect(gamresultsum.df.ADHD$parcel[x], "SC.")){
    subtitle <- bquote(
        italic('F') == .(round(gamresultsum.df.ADHD.SC.ABCDsig$gam.smooth.F[x], 2)) * "," ~ 
          italic(P) == .(round(gamresultsum.df.ADHD.SC.ABCDsig$bootstrap_p.fdr[x], 3))
      )
    title=paste0("Rank=", SCrank.tmp)
    
  }else{
    subtitle <- bquote(
        italic('F') == .(round(gamresultsum.df.ADHD.SC.ABCDsig$gam.smooth.F[(x - 9)], 2)) * "," ~ 
          italic(P) == .(round(gamresultsum.df.ADHD.SC.ABCDsig$bootstrap_p.fdr[(x - 9)], 3))
      )
    title=NULL
  }
  
  PointFig <- ggplot(data=data.ADHD)+
    geom_point(data=SCdata.ADHD, aes(x=age, y=Deviation), color= "#810F7C", alpha=0.3)+
    geom_ribbon(aes(x=age, ymin=selo, ymax=sehi), fill="#810F7C", alpha=0.3)+
    geom_line(aes(x=age, y=fit), linewidth=1)+
    scale_x_continuous(breaks = c(9, 11, 13, 15))+
      scale_y_continuous(breaks = c(-4, -2, 0, 2, 4))+
      labs(x="Age (years)", y="SC deviation")+
      theme_classic()+
      theme(axis.text=element_text(size=24, color="black"), 
            axis.title =element_text(size=24, color="black"),aspect.ratio = 1.1,
            plot.title = element_text(size=20.5, hjust=0.5, color="black"),
            plot.background=element_rect(fill="transparent"),
            panel.background=element_rect(fill="transparent"),
            legend.position = 'none')
  
  
  ggsave(paste0(FigureFolder, "/SCstrength_Age/Deviationcompare/DeviationChange/ADHD_", region, "_Point.tiff"), PointFig, width=13, height = 13, units = "cm")
  
  
}
Yeo_10$SClabel <- paste0(Yeo_10$SClabel, "_deviationZ")
gamresultsum.df.ADHD.SC.ABCDsig <- gamresultsum.df.ADHD.SC.ABCDsig %>% left_join(Yeo_10, join_by(parcel==SClabel))

write.csv(gamresultsum.df.ADHD.symp, paste0(resultFolder, "/SymptomChange_gamresults_ADHD.csv"), row.names = F)
write.csv(gamresultsum.df.ADHD.SC.ABCDsig, paste0(resultFolder, "/SCDeviationChange_gamresults_ADHD_ABCDoverlap.csv"), row.names = F)

```

# Plot effect size
```{r}
## Plot effect size
lmthr <- max(abs(c(gamresultsum.df.ADHD.SC$partialRsq, gamresultsum.df.TD$partialRsq)))
# ADHD
SCrankcorr(gamresultsum.df.ADHD.SC, "partialRsq", Yeoresolution.delLM)
# ADHD
# 15	partialRsq	r=-0.3544105	P=7.143925e-05	

# scatter plot
df <- SCrankcorr(gamresultsum.df.ADHD.SC, "partialRsq", Yeoresolution.delLM, T)

scatter <- ggplot(data=df)+
    geom_point(aes(x=SCrank, y=partialRsq), size=1.8, color="#B2182B")+
    geom_smooth(aes(x=SCrank, y=partialRsq), method ="lm", color="black", linewidth=1.2)+
    #scale_color_distiller(type="seq", palette = "RdBu", limits=c(-lmthr, lmthr),direction = -1)+
    labs(x="S-A connectional axis rank", y = expression("Age effect (partial " * italic(R)^2 * ")"))+
    #scale_y_continuous(breaks = c(-0.015, -0.010, -0.005,0, 0.005, 0.010), labels = c(-15,-10, -5, 0, 5, 10))+
    #scale_y_continuous(breaks = c(-0.003,0, 0.003, 0.006), labels = c(-3, 0, 3, 6))+
    scale_x_continuous(breaks = c(0,20,40,60,80,100,120))+
    theme_classic()+
    theme(axis.text=element_text(size=20.3, color="black"), 
        axis.title =element_text(size=20.3, color="black"),aspect.ratio = 1.03,
        plot.background=element_rect(fill="white"),
        panel.background=element_rect(fill="white"),
        plot.title = element_text(size=16, hjust = 0.5),
        legend.position = "none")

ggsave(paste0(FigureFolder, '/SCstrength_Age/Deviationcompare/DeviationRsqADHD_SCrankcorr.tiff'),scatter, width=15.2, height =15.4, units = "cm")

# Matrix
gamresultsum.df.ADHD.SC <- gamresultsum.df.ADHD.SC %>% mutate(
  bootstrap_p.fdr2 = case_when(parcel %in% Int.results.df_final2$parcel[Int.results.df_final2$anova.int.pvalue.fdr < 0.05] ~ 0.001,
                               .default = 1)
)

axeslabels=c("VS.P", "SM.A", "VS.C", "SM.B", "DA.A", "DA.B", "FP.C", "DM.C", "VA.A", "TP", "FP.A", "VA.B", "DM.A", "FP.B", "DM.B") 
axeslabelsGap=T
PaletteSet <- list(Name="RdBu", drirection=-1, lmmin = -lmthr, lmmax = lmthr, anglex=45, angley=45,hjustx = 1, hjusty = 1, vjustx = 1, vjusty=0.5)

FigintR2 <- plotmatrix(dataname="gamresultsum.df.ADHD.SC", "partialRsq", ds.resolution=Yeoresolution.delLM, Pvar="bootstrap_p.fdr2", NAcol="white", lmthr=lmthr, axeslabels, axeslabelsGap=T, linerange_frame=NA, Pvar.noFDR=NA)

print(FigintR2)

ggsave(paste0(FigureFolder, "/SCstrength_Age/Deviationcompare/Matrix", Yeoresolution.delLM,"_DeviationAge_Rsq_ADHD_addintP.tiff"),FigintR2, height=16, width=18, units = "cm")


# TD
SCrankcorr(gamresultsum.df.TD, "partialRsq", Yeoresolution.delLM)
# TD
# 15	partialRsq	r=0.07304132  P=0.4278871

# scatter plot
df <- SCrankcorr(gamresultsum.df.TD, "partialRsq", Yeoresolution.delLM, T)

scatter <- ggplot(data=df)+
    geom_point(aes(x=SCrank, y=partialRsq, color=partialRsq), size=5)+
    geom_smooth(aes(x=SCrank, y=partialRsq), method ="lm", color="black", linewidth=1.2)+
    scale_color_distiller(type="seq", palette = "RdBu", limits=c(-lmthr, lmthr), direction = -1)+
    labs(x="S-A connectional axis rank", y = expression("Age effect (partial " * italic(R)^2 * ")"))+
    #scale_y_continuous(breaks = c(-0.015, -0.010, -0.005,0, 0.005, 0.010), labels = c(-15,-10, -5, 0, 5, 10))+
    #scale_y_continuous(breaks = c(-0.003,0, 0.003, 0.006), labels = c(-3, 0, 3, 6))+
    scale_x_continuous(breaks = c(0,20,40,60,80,100,120))+
    theme_classic()+
    theme(axis.text=element_text(size=23, color="black"), 
          axis.title =element_text(size=23),aspect.ratio = 1,
          axis.line = element_line(linewidth=0.6),axis.ticks= element_line(linewidth=0.6),
          plot.title = element_text(size=20, hjust = 0.5, vjust=2),
          plot.background=element_rect(fill="transparent"),
          panel.background=element_rect(fill="transparent"),
          legend.position = "none")
ggsave(paste0(FigureFolder, '/SCstrength_Age/Deviationcompare/DeviationRsqTD_SCrankcorr.tiff'),scatter, width=15, height =15, units = "cm")


# Matrix
lmthr <- max(abs(c(gamresultsum.df.ADHD.SC$partialRsq, gamresultsum.df.TD$partialRsq)))
axeslabels=c("VS.P", "SM.A", "VS.C", "SM.B", "DA.A", "DA.B", "FP.C", "DM.C", "VA.A", "TP", "FP.A", "VA.B", "DM.A", "FP.B", "DM.B") 
axeslabelsGap=T
PaletteSet <- list(Name="RdBu", drirection=-1, lmmin = -lmthr, lmmax = lmthr, anglex=45, angley=45,hjustx = 1, hjusty = 1, vjustx = 1, vjusty=0.5)

FigintR2 <- plotmatrix(dataname="gamresultsum.df.TD", "partialRsq", ds.resolution=Yeoresolution.delLM, Pvar="bootstrap_p.fdr", NAcol="white", lmthr=lmthr, axeslabels, axeslabelsGap=T, linerange_frame=NA, Pvar.noFDR=NA)

print(FigintR2)

ggsave(paste0(FigureFolder, "/SCstrength_Age/Deviationcompare/Matrix", Yeoresolution.delLM,"_DeviationAge_Rsq_TD.tiff"),FigintR2, height=16, width=18, units = "cm")



```
